### ISSUE TITLE
Uncaught TypeError when splitting tabs

### ISSUE THREAD

**Issue by andrewjensen** [MoOx/atom-smart-tab-name#10]
An error is getting thrown when I try to split a tab. It is thrown whether I use the context menu or the (cmd+k, right) keybinding. I believe this only just started happening after upgrading to v1.0.4.

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [smart-tab-name](https://github.com/MoOx/atom-smart-tab-name) package, v1.0.4
### Stack Trace

Uncaught TypeError: pane.onDidMoveItem is not a function

```
At /Users/andrew/.atom/packages/smart-tab-name/lib/smart-tab-name.coffee:119

TypeError: pane.onDidMoveItem is not a function
    at /Users/andrew/.atom/packages/smart-tab-name/lib/smart-tab-name.coffee:119:27
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at PaneContainer.module.exports.PaneContainer.didAddPane (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:288:27)
    at Pane.module.exports.Pane.setContainer (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:100:26)
    at PaneAxis.module.exports.PaneAxis.addChild (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:142:13)
    at PaneAxis.module.exports.PaneAxis.insertChildAfter (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:214:19)
    at Pane.module.exports.Pane.split (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:720:23)
    at Pane.module.exports.Pane.splitRight (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:686:19)
    at TabBarView.module.exports.TabBarView.splitTab (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:427:31)
    at Object.addElementCommands.tabs:split-right (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:135:26)
```
### Commands

```
     -0:27 core:close (div.markdown-preview.native-key-bindings)
     -0:25.6.0 markdown-preview:toggle (atom-text-editor.editor.is-focused)
     -0:23.8.0 pane:split-right (div.markdown-preview.native-key-bindings)
     -0:21.1.0 core:cancel (div.markdown-preview.native-key-bindings)
     -0:19.7.0 pane:split-right (div.markdown-preview.native-key-bindings)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "file-icons"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
language-elixir, v0.5.2
language-javascript-jsx, v0.3.7
language-racket, v0.4.0
smart-tab-name, v1.0.4

# Dev
No dev packages
```
