### PR TITLE
:bug: fix #11 SmartTabName when panes are split

### LINKED ISSUE #10: Uncaught TypeError when splitting tabs
An error is getting thrown when I try to split a tab. It is thrown whether I use the context menu or the (cmd+k, right) keybinding. I believe this only just started happening after upgrading to v1.0.4.

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [smart-tab-name](https://github.com/MoOx/atom-smart-tab-name) package, v1.0.4
### Stack Trace

Uncaught TypeError: pane.onDidMoveItem is not a function

```
At /Users/andrew/.atom/packages/smart-tab-name/lib/smart-tab-name.coffee:119

TypeError: pane.onDidMoveItem is not a function
    at /Users/andrew/.atom/packages/smart-tab-name/lib/smart-tab-name.coffee:119:27
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at PaneContainer.module.exports.PaneContainer.didAddPane (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:288:27)
    at Pane.module.exports.Pane.setContainer (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:100:26)
    at PaneAxis.module.exports.PaneAxis.addChild (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:142:13)
    at PaneAxis.module.exports.PaneAxis.insertChildAfter (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:214:19)
    at Pane.module.exports.Pane.split (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:720:23)
    at Pane.module.exports.Pane.splitRight (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:686:19)
    at TabBarView.module.exports.TabBarView.splitTab (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:427:31)
    at Object.addElementCommands.tabs:split-right (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:135:26)
```
### Commands

```
     -0:27 core:close (div.markdown-preview.native-key-bindings)
     -0:25.6.0 markdown-preview:toggle (atom-text-editor.editor.is-focused)
     -0:23.8.0 pane:split-right (div.markdown-preview.native-key-bindings)
     -0:21.1.0 core:cancel (div.markdown-preview.native-key-bindings)
     -0:19.7.0 pane:split-right (div.markdown-preview.native-key-bindings)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "file-icons"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
language-elixir, v0.5.2
language-javascript-jsx, v0.3.7
language-racket, v0.4.0
smart-tab-name, v1.0.4

# Dev
No dev packages
```

### LINKED ISSUE #11: Uncaught TypeError: pane.onDidMoveItem is not a function
Tried to split right with 2 files open, name tmux.conf and tmux.conf.save

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [smart-tab-name](https://github.com/MoOx/atom-smart-tab-name) package, v1.0.4
### Stack Trace

Uncaught TypeError: pane.onDidMoveItem is not a function

```
At /Users/bedge/.atom/packages/smart-tab-name/lib/smart-tab-name.coffee:119

TypeError: pane.onDidMoveItem is not a function
  at /Users/bedge/.atom/packages/smart-tab-name/lib/smart-tab-name.coffee:119:27
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.didAddPane (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:288:27)
  at Pane.module.exports.Pane.setContainer (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:100:26)
  at PaneAxis.module.exports.PaneAxis.addChild (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:142:13)
  at PaneAxis.module.exports.PaneAxis.insertChildAfter (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:214:19)
  at Pane.module.exports.Pane.split (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:720:23)
  at Pane.module.exports.Pane.splitRight (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:686:19)
  at TabBarView.module.exports.TabBarView.splitTab (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:427:31)
  at Object.addElementCommands.tabs:split-right (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:135:26)
  at space-pen-ul.commandsWithPropagationStopped.(anonymous function) (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:86:36)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:145:19)
  at [object Object].jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:172:7)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:140:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:157:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "disabledPackages": [
      "symbols-view",
      "semanticolor",
      "ctags-status",
      "select-rectangle"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-ctags, v4.3.0
atom-html-preview, v0.1.11
atom-material-syntax, v0.2.4
atom-material-ui, v0.6.2
atom-python-debugger, v0.3.4
autocomplete-ctags, v0.3.2
autocomplete-plus-python-jedi, v0.3.6
color-picker, v2.0.13
color-tabs, v0.1.8
colorful-json, v1.0.0
docblockr, v0.7.3
git-diff-details, v0.20.0
git-log, v0.4.1
gradle-ci, v1.1.4
java-importer, v1.4.1
language-gradle, v0.0.3
language-groovy, v0.4.0
language-tmux, v0.4.0
linter, v1.8.1
linter-javac, v1.2.0
linter-python-pep8, v0.2.0
linter-python-pyflakes, v0.1.0
linter-shellcheck, v1.0.2
markdown-mindmap, v0.2.4
minimap, v4.13.4
minimap-bookmarks, v0.1.0
minimap-codeglance, v0.4.2
minimap-find-and-replace, v4.3.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-linter, v1.0.0
minimap-pigments, v0.1.7
minimap-selection, v4.3.1
pigments, v0.15.0
smart-tab-name, v1.0.4
tab-smart-sort, v0.1.4
tag, v0.3.0
tree-view-git-modified, v0.5.12
tree-view-git-status, v0.2.2
typewriter, v0.3.4

# Dev
No dev packages
```

### PR DESCRIPTION
**Pull request by bmenant**
Change `pane` to `event.pane` since `onDidAddPane` callbacks take an
event as parameter.
Use fat-arrow `=>` to reference `@disposables` from the callback.
Dispose `onDidMoveItem` events with `@disposables.add` method.

Fix #11
Fix #10

### CODE REVIEW

**Comment by MoOx** [comment]
Thanks for this.

**Comment by MoOx** [comment]
Released as 1.0.5
